---
name: deploy-to-gcs

on:
  push:
    branches:
      - live

env:
  GCS_BUCKET: joelplm_prebidfledgetest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'

      - name: build prebid.js
        run: |
          npm install gulp-cli -g
          npm ci
          gulp build --modules=openxBidAdapter,openxRtbAdapter --sourceMaps=true

      - name: publish prebid.js
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'build/dist/prebid.js.*'
          destination_repo: 'joelpm/adcountability.com'
          destination_folder: 'js/vendor/'
          user_email: 'joel.meyer@gmail.com'
          user_name: 'joelpm'
          commit_message: 'auto-publish of prebid.js'
          use_rsync: true