---
name: deploy-to-gcs

on:
  push:
    branches:
      - live

env:
  GCS_BUCKET: joelplm_prebidfledgetest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          
      - name: gcloud setup
        uses: google-github-actions/setup-gcloud@v0
        with:
          export_default_credentials: true

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'

      - name: build prebid.js
        run: |
          npm install gulp-cli -g
          gulp build --modules=openxBidAdapter,openxRtbAdapter

      - name: deploy prebid.js
        run: |
          gsutil cp build/dist/prebid.js gs://${GCS_BUCKET}/prebid/prebid.js;