---
name: deploy-to-adcountability

on:
  push:
    branches:
      - live

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'

      - name: build prebid.js
        run: |
          npm install gulp-cli -g
          npm ci
          gulp build --modules=openxRtbAdapter,consentManagement --sourceMaps=true

      - name: publish prebid.js
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'build/dist/'
          target-directory: 'js/vendor/prebid/'
          destination-github-username: 'joelpm'
          destination-repository-name: 'adcountability.com'
          user-email: joel.meyer@gmail.com
          target-branch: main